### ISSUE TITLE
No way to configure the passport "Asynchronous configuration retrieval"

### ISSUE THREAD

**Issue by ineedbots** [feathersjs-ecosystem/feathers-authentication-ldap#30]
There are some instances where we need to have an asynchronous retrieval for the configuration of the LDAP settings every time we make a request.

This explains how to achieve this by passing in a function rather than an object to the new strategy's instance.
https://github.com/vesse/passport-ldapauth#asynchronous-configuration-retrieval

Current there is no way to pass a function into this feathers auth strategy.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs-ecosystem/feathers-authentication-ldap/pull/24
